name: Deploy to Digital Ocean
on:
  push:
    branches: [ main ]  # Make sure this matches your main branch name (could be 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/resume-site"
        strip_components: 1

    - name: Set permissions and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/resume-site
          sudo chmod -R 755 /var/www/resume-site
          sudo systemctl restart nginx