name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DO_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

    - name: Create dist directory on server
      run: ssh ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }} 'mkdir -p /var/www/resume-site'

    - name: Transfer and deploy
      run: |
        tar -czf dist.tar.gz -C dist .
        scp dist.tar.gz ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }}:/var/www/resume-site/
        ssh ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }} '
          cd /var/www/resume-site &&
          tar xzf dist.tar.gz &&
          rm dist.tar.gz &&
          sudo chown -R www-data:www-data . &&
          sudo chmod -R 755 . &&
          sudo systemctl restart nginx
        '